### ISSUE TITLE
Quote-wrapped queries occasionally throw 500 errors

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#43] opened 2018-01-16 07:40 UTC
* Works: https://content-search.example.org/cc842mn9348/search?q=crime%20against%20humanity
* Works: https://content-search.example.org/cc842mn9348/search?q=crimes%20against%20humanity
* Works: https://content-search.example.org/cc842mn9348/search?q="crimes%20against%20humanity"
* Throws a 500: https://content-search.example.org/cc842mn9348/search?q="crime%20against%20humanity"
* Throws a 500: https://content-search.example.org/cc842mn9348/search?q=%22crime%20against%20humanity%22
* Does not throw a 500, but just returns an empty result set: https://content-search.example.org/cc842mn9348/search?q=%22crimes%20against%20humanity%22

**Comment by cbeer** [comment] 2018-01-16 22:52
Duplicate of #41.

**Closed by cbeer** 2018-01-16 22:52 UTC
Labels: bug
